[alias]
git-amend = "run --bin git-amend --"
git-bump = "run --bin git-bump --"
git-c = "run --bin git-c --"
git-changelog = "run --bin git-changelog --"
git-install-hooks = "run --bin git-install-hooks --"
git-lint = "run --bin git-lint --"
git-release = "run --bin git-release --"

[env]
RUST_LOG = "off"
