[commits]
types_inc_minor = ["feat"]

[commits.types]
build = "Build system"
cd = "Continuous Delivery"
chore = "Other changes"
ci = "Continuous Integration"
docs = "Documentation"
feat = "A new feature"
fix = "Bug fixes"
perf = "Performance Improvements"
refactor = "Code refactoring"
style = "Code styling"
test = "Tests"

[changelog]
