[commit]
types_inc_minor = ["feat"]

[commit.types]
build = "Build system"
cd = "Continuous Delivery"
chore = "Other changes"
ci = "Continuous Integration"
docs = "Documentation"
feat = "A new feature"
fix = "Bug fixes"
perf = "Performance Improvements"
refactor = "Code refactoring"
style = "Code styling"
test = "Tests"

[hooks]
pre-commit = ["cargo hello", "cargo build2"]

[changelog.types]
build = "Build system"
cd = "Continuous Delivery"
chore = "Other changes"
ci = "Continuous Integration"
docs = "Documentation changes"
feat = "New features"
fix = "Bug fixes"
perf = "Performance Improvements"
refactor = "Code refactoring"
style = "Code styling changes"
test = "Tests"

[release]
bump_commands = []
