[commit]
types_inc_minor = ["feat"]

[commit.types]
build = "Build system"
cd = "Continuous Delivery"
chore = "Other changes"
ci = "Continuous Integration"
docs = "Documentation"
feat = "New features"
fix = "Bug fixes"
perf = "Performance Improvements"
refactor = "Code refactoring"
style = "Code styling"
test = "Tests"

[hooks]
pre-commit = ["cargo clippy"]

[changelog]
types = ["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "cd", "chore"]

[release]
bump_commands = [
  "cargo set-version {{version}}",
  "cargo update",
]
