name: ci

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

jobs:
  ci-lint:
    name: CI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          profile: default

      - name: Clippy
        run: |
          cargo --version
          cargo clippy

  ci-build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          profile: default

      - name: Build
        run: cargo build
