name: cd

on:
  push:
    # Trigger this workflow only on commits pushed with a tag
    tags:
      - "*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Dagger jobs
        uses: dagger/dagger-for-github@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
          RELEASE_VERSION: ${{ github.ref_name }}
        # See all options at https://github.com/dagger/dagger-for-github
        with:
          # To pin external dependencies, you can use `project update github.com/[package-source]@v[n]`
          cmds: |
            project update
            do release
            do publish
